### ISSUE TITLE
It is impossible to sort by association's fields

### ISSUE THREAD

**Issue by kirushik** [mynameisrufus/sorted#21]
Let's say we have `User` class, which belongs to an `Organization` class.

In the sorted 1.0 it was possible to pass `'organizations.name'` to `sorted` method on `User.references(:organization).includes(:organization)`, and have our users list sorted by an association name (quite handy in admin views, for example).

With sorted 2.0 that seems no longer the case — it tries to sort by `"users"."organizations.name"`, and that of course fails.

I think this is either an unintended regression in sorted 2.0, or plainly a missing feature.

**Comment by mynameisrufus** [comment]
Thanks @kirushik, I will have a look at this tomorrow, thanks for the detail.

**Comment by mynameisrufus** [comment]
@kirushik are you using `sorted-activerecord` or `sorted`? Could you please close this ticket and open it on https://github.com/mynameisrufus/sorted-activerecord with the code you trying to run, even better if you could provide me with a failing test, that would be very helpful :smiley:

**Comment by kirushik** [comment]
@mynameisrufus OK, will do that today.
